# conf/hydra/launcher/slurm_launcher.yaml
# @package hydra.launcher
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher

account: biyik_1165
slurm_partition: gpu
nodes: 1
ntasks_per_node: 1
cpus_per_task: 8
gpus_per_node: 1
slurm_gres: gpu:v100
mem_gb: 16
timeout_min: 240

setup:
  - module purge
  - module load gcc/11.3.0
  - source /spack/conda/miniforge3/24.3.0/etc/profile.d/conda.sh && conda activate intervention_rl

slurm_constraint: ""
slurm_qos: ""
submitit_folder: ${hydra.sweep.dir}/${hp_name}/.submitit/%j
name: ${hydra.job.name}