defaults: 
    - base

# Environment-specific hyperparameters
name: 'PongNoFrameskip-v4'
short_name: 'pong'
new_action: 2
catastrophe_clearance: 8
blocker_clearance: 8
obs_dim: 1
action_dim: 6
max_timesteps: 1000
n_envs: 16
n_stack: 4

# Blocker-related hyperparameters
alpha: 0.01  # Alpha coefficient for reward modification
beta: 0.01   # Beta coefficient for reward modification